function getEnglishName(nameInGerman) {

  if ((countryList[nameInGerman] === undefined) || (countryList[nameInGerman] === null)) 
  {
    console.log("Name not found for: " + nameInGerman);
    return "ERROR";
  }

  return countryList[nameInGerman];
}

const countryList = {
  "aegypten" : "Egypt",
  "albanien" : "Albania",
  "andorra" : "Andorra",
  "argentinien" : "Argentina",
  "australien" : "Australia",
  "bahamas" : "Bahamas",
  "barbados" : "Barbados",
  "belgien" : "Belgium",
  "bhutan" : "Bhutan",
  "bolivien" : "Bolivia",
  "bosnien-und-herzegowina" : "Bosnia and Herzegovina",
  "botswana" : "Botswana",
  "brasilien" : "Brazil",
  "bulgarien" : "Bulgaria",
  "chile" : "Chile",
  "china" : "China",
  "costa-rica" : "Costa Rica",
  "daenemark" : "Denmark",
  "deutschland" : "Germany",
  "dominikanische-republik" : "Dominican Republic",
  "ecuador" : "Ecuador",
  "el-salvador" : "El Salvador",
  "estland" : "Estonia",
  "finnland" : "Finland",
  "frankreich" : "France",
  "gambia" : "Gambia",
  "ghana" : "Ghana",
  "griechenland" : "Greece",
  "grossbritannien" : "Great Britain",
  "guatemala" : "Guatemala",
  "honduras" : "Honduras",
  "hongkong" : "Hong Kong",
  "indien" : "India",
  "indonesien" : "Indonesia",
  "irland" : "Ireland",
  "island" : "Iceland",
  "israel" : "Israel",
  "italien" : "Italy",
  "jamaika" : "Jamaica",
  "japan" : "Japan",
  "jordanien" : "Jordan",
  "kambodscha" : "Cambodia",
  "kanada" : "Canada",
  "kap-verde" : "Cape Verde",
  "katar" : "Qatar",
  "kenia" : "Kenya",
  "kolumbien" : "Columbia",
  "kosovo" : "Kosovo",
  "kroatien" : "Croatia",
  "kuba" : "Cuba",
  "lettland" : "Latvia",
  "liechtenstein" : "Liechtenstein",
  "litauen" : "Lithuania",
  "luxemburg" : "Luxembourg",
  "madagaskar" : "Madagascar",
  "malaysia" : "Malaysia",
  "malediven" : "Maldives",
  "malta" : "Malta",
  "marokko" : "Morocco",
  "mauretanien" : "Mauritania",
  "mauritius" : "Mauritius",
  "mexiko" : "Mexico",
  "moldau" : "Moldova",
  "monaco" : "Monaco",
  "montenegro" : "Montenegro",
  "mosambik" : "Mozambique",
  "myanmar" : "Myanmar",
  "namibia" : "Namibia",
  "nepal" : "Nepal",
  "neuseeland" : "New Zealand",
  "niederlande" : "Netherlands",
  "nordmazedonien" : "North Macedonia",
  "norwegen" : "Norway",
  "oesterreich" : "Austria",
  "oman" : "Oman",
  "panama" : "Panama",
  "peru" : "Peru",
  "philippinen" : "Philippines",
  "polen" : "Poland",
  "portugal" : "Portugal",
  "rumaenien" : "Romania",
  "russland" : "Russia",
  "sambia" : "Zambia",
  "san-marino" : "San Marino",
  "schweden" : "Sweden",
  "schweiz" : "Switzerland",
  "serbien" : "Serbia",
  "seychellen" : "Seychelles",
  "singapur" : "Singapore",
  "slowakei" : "Slovakia",
  "slowenien" : "Slovenia",
  "spanien" : "Spain",
  "sri-lanka" : "Sri Lanka",
  "st-lucia" : "St Lucia",
  "suedafrika" : "South Africa",
  "suedkorea" : "South Korea",
  "taiwan" : "Taiwan",
  "taiwan" : "Taiwan",
  "tansania" : "Tanzania",
  "thailand" : "Thailand",
  "thailand" : "Thailand",
  "tschechien" : "Czech Republic",
  "tuerkei" : "Turkey",
  "tunesien" : "Tunisia",
  "uganda" : "Uganda",
  "ukraine" : "Ukraine",
  "ungarn-" : "Hungary",
  "uruguay" : "Uruguay",
  "usa" : "USA",
  "venezuela" : "Venezuela",
  "vereinigte-arabische-emirate" : "United Arab Emirates",
  "vietnam" : "Vietnam",
  "weissrussland-belarus" : "Belarus",
  "zypern" : "Cyprus"
};